/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.message.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the t_student service. Represents a row in the &quot;message_t_student&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.message.model.impl.t_studentModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.message.model.impl.t_studentImpl}.
 * </p>
 *
 * @author mazhe
 * @see t_student
 * @see com.message.model.impl.t_studentImpl
 * @see com.message.model.impl.t_studentModelImpl
 * @generated
 */
public interface t_studentModel extends BaseModel<t_student> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a t_student model instance should use the {@link t_student} interface instead.
	 */

	/**
	 * Returns the primary key of this t_student.
	 *
	 * @return the primary key of this t_student
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this t_student.
	 *
	 * @param primaryKey the primary key of this t_student
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the student ID of this t_student.
	 *
	 * @return the student ID of this t_student
	 */
	public long getStudentId();

	/**
	 * Sets the student ID of this t_student.
	 *
	 * @param studentId the student ID of this t_student
	 */
	public void setStudentId(long studentId);

	/**
	 * Returns the group ID of this t_student.
	 *
	 * @return the group ID of this t_student
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this t_student.
	 *
	 * @param groupId the group ID of this t_student
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this t_student.
	 *
	 * @return the company ID of this t_student
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this t_student.
	 *
	 * @param companyId the company ID of this t_student
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this t_student.
	 *
	 * @return the user ID of this t_student
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this t_student.
	 *
	 * @param userId the user ID of this t_student
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this t_student.
	 *
	 * @return the user uuid of this t_student
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this t_student.
	 *
	 * @param userUuid the user uuid of this t_student
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this t_student.
	 *
	 * @return the user name of this t_student
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this t_student.
	 *
	 * @param userName the user name of this t_student
	 */
	public void setUserName(String userName);

	/**
	 * Returns the passwd of this t_student.
	 *
	 * @return the passwd of this t_student
	 */
	@AutoEscape
	public String getPasswd();

	/**
	 * Sets the passwd of this t_student.
	 *
	 * @param passwd the passwd of this t_student
	 */
	public void setPasswd(String passwd);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.message.model.t_student t_student);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.message.model.t_student> toCacheModel();

	@Override
	public com.message.model.t_student toEscapedModel();

	@Override
	public com.message.model.t_student toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}