/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.message.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.message.model.t_message;

import com.message.service.t_messageLocalServiceUtil;

/**
 * The extended model base implementation for the t_message service. Represents a row in the &quot;message_t_message&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link t_messageImpl}.
 * </p>
 *
 * @author mazhe
 * @see t_messageImpl
 * @see com.message.model.t_message
 * @generated
 */
public abstract class t_messageBaseImpl extends t_messageModelImpl
	implements t_message {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a t_message model instance should use the {@link t_message} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			t_messageLocalServiceUtil.addt_message(this);
		}
		else {
			t_messageLocalServiceUtil.updatet_message(this);
		}
	}
}