/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.message.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.message.model.t_teacher;

import com.message.service.t_teacherLocalServiceUtil;

/**
 * The extended model base implementation for the t_teacher service. Represents a row in the &quot;message_t_teacher&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link t_teacherImpl}.
 * </p>
 *
 * @author mazhe
 * @see t_teacherImpl
 * @see com.message.model.t_teacher
 * @generated
 */
public abstract class t_teacherBaseImpl extends t_teacherModelImpl
	implements t_teacher {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a t_teacher model instance should use the {@link t_teacher} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			t_teacherLocalServiceUtil.addt_teacher(this);
		}
		else {
			t_teacherLocalServiceUtil.updatet_teacher(this);
		}
	}
}